on:
  schedule:
    - cron:  '0 6 * * *'
    # scheduled at 06:00 everyday
  workflow_dispatch:
    # to run manual builds

jobs:
  build_and_deploy_hugo_site:
    runs-on: ubuntu-latest
    name: Build and deploy Hugo site

    steps:
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.88.1'
    
    - name: Checkout repo on source_branch
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        token: ${{ secrets.MY_SECRET }}   # <<if needed for private repos>>
        fetch-depth: '0'
        # <<fetch-depth: '0' currently required until shallow clone problems are solved>>
        
    - name: Build site and push to release branch
      uses: aormsby/hugo-deploy-to-pages@v2.1
      id: build_step
      with:
        source_branch: 'main'
        release_branch: 'github-page'
        full_rebuild: true
        commit_message: "Auto daily build."

